S = CODE|LABEL
<CODE> = <SPACE*> (A-INSTRUCTION|C-INSTRUCTION) <SPACE*> COMMENT*
SPACE = ' '
LABEL = <SPACE*> <'('> #"[A-Za-z][A-Za-z\d_\.\$:]*" <')'> <SPACE*>
COMMENT = <FORWARDSLASH FORWARDSLASH> COMMENT-TEXT
COMMENT-TEXT = #".*"
FORWARDSLASH = '/'
EMPTYLINE = ""
ENDOFLINE = (CARRIAGERETURN|NEWLINE)+
NEWLINE = '\n'
CARRIAGERETURN = '\r'

A-INSTRUCTION = '@' (NUMBER|VARIABLE)
NUMBER = #"\d+"
VARIABLE = #"[A-Za-z][A-Za-z\d_\.\$:]*"
C-INSTRUCTION = (DEST <'='>)* COMPUTE JUMP*
DEST = (REGISTER|MEMORY) (REGISTER|MEMORY)* (REGISTER|MEMORY)*
COMPUTE = ZERO|ONE|MINUSONE|DREG|AREG|NOTDREG|NOTAREG|MINUSD|MINUSA|INCD|INCA|DECD|DECA|DPLUSA|DMINUSA|AMINUSD|DANDA|DORA|M|NOTM|MINUSM|INCM|DECM|DPLUSM|DMINUSM|MMINUSD|DANDM|DORM 
ZERO = '0'
ONE = '1'
MINUSONE = '-1'
DREG = 'D'
AREG = 'A'
NOTDREG = '!D'
NOTAREG = '!A'
MINUSD = '-D'
MINUSA = '-A'
INCD = 'D+1'
INCA = 'A+1'
DECD = 'D-1'
DECA = 'A-1'
DPLUSA = 'D+A'
DMINUSA = 'D-A'
AMINUSD = 'A-D'
DANDA = 'D&A'
DORA = 'D|A'
M = 'M'
NOTM = '!M'
MINUSM = '-M'
INCM = 'M+1'
DECM = 'M-1'
DPLUSM = 'D+M'
DMINUSM = 'D-M'
MMINUSD = 'M-D'
DANDM = 'D&M'
DORM = 'D|M'
REGISTER = 'A'|'D'
MEMORY = 'M'
OPERATOR = '+'|'-'
JUMP = <';'> (JGT|JEQ|JGE|JLT|JNE|JLE|JMP)
JGT = 'JGT'
JEQ = 'JEQ'
JGE = 'JGE'
JLT = 'JLT'
JNE = 'JNE'
JLE = 'JLE'
JMP = 'JMP'