S = COMMENT|EMPTYLINE |CODE
COMMENT = <FORWARDSLASH FORWARDSLASH> COMMENT-TEXT
COMMENT-TEXT = #".*"
FORWARDSLASH = '/'
EMPTYLINE = ""
ENDOFLINE = (CARRIAGERETURN|NEWLINE)+
NEWLINE = '\n'
CARRIAGERETURN = '\r'
<CODE> = A-INSTRUCTION|C-INSTRUCTION
A-INSTRUCTION = '@' NUMBER
NUMBER = #"\d+"
C-INSTRUCTION = (DEST <'='>)* COMPUTE JUMP*
DEST = REGISTER|MEMORY
COMPUTE = ZERO|ONE|MINUSONE|DREG|AREG|NOTDREG|NOTAREG|MINUSD|MINUSA|INCD|INCA|DECD|DECA|DPLUSA|DMINUSA|AMINUSD|DANDA|DORA|M|NOTM|MINUSM|INCM|DECM|DPLUSM|DMINUSM|MMINUSD|DANDM|DORM 
ZERO = '0'
ONE = '1'
MINUSONE = '-1'
DREG = 'D'
AREG = 'A'
NOTDREG = '!D'
NOTAREG = '!A'
MINUSD = '-D'
MINUSA = '-A'
INCD = 'D+1'
INCA = 'A+1'
DECD = 'D-1'
DECA = 'A-1'
DPLUSA = 'D+A'
DMINUSA = 'D-A'
AMINUSD = 'A-D'
DANDA = 'D&A'
DORA = 'D|A'
M = 'M'
NOTM = '!M'
MINUSM = '-M'
INCM = 'M+1'
DECM = 'M-1'
DPLUSM = 'D+M'
DMINUSM = 'D-M'
MMINUSD = 'M-D'
DANDM = 'D&M'
DORM = 'D|M'
REGISTER = 'A'|'D'
MEMORY = 'M'
OPERATOR = '+'|'-'
JUMP = ';' 'JGT'